-- DataCore Marketing Studio — Supabase Schema
-- Run this in the Supabase SQL Editor to create the tables

-- Content pieces generated by the agent
CREATE TABLE IF NOT EXISTS content (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  task_type TEXT NOT NULL,
  platform TEXT,
  topic TEXT NOT NULL,
  copy TEXT NOT NULL,
  hashtags TEXT[] DEFAULT '{}',
  visual_suggestion TEXT,
  variant_b TEXT,
  brand_verdict TEXT DEFAULT 'PENDIENTE',
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Editorial calendar entries
CREATE TABLE IF NOT EXISTS calendar_entries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  date DATE NOT NULL,
  platform TEXT NOT NULL,
  format TEXT NOT NULL,
  pillar TEXT NOT NULL,
  topic TEXT NOT NULL,
  time TEXT NOT NULL,
  content_id UUID REFERENCES content(id),
  status TEXT DEFAULT 'pendiente',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Lead tracking
CREATE TABLE IF NOT EXISTS leads (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  company TEXT,
  role TEXT,
  message TEXT NOT NULL,
  temperature TEXT NOT NULL DEFAULT 'FRIO',
  next_step TEXT,
  suggested_message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Agent task history
CREATE TABLE IF NOT EXISTS agent_tasks (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  type TEXT NOT NULL,
  topic TEXT NOT NULL,
  platform TEXT,
  status TEXT DEFAULT 'running',
  steps_json JSONB,
  result_json JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (but allow all for MVP — internal tool)
ALTER TABLE content ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_tasks ENABLE ROW LEVEL SECURITY;

-- Allow all operations for anon (MVP — no auth)
CREATE POLICY "Allow all on content" ON content FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on calendar_entries" ON calendar_entries FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on leads" ON leads FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on agent_tasks" ON agent_tasks FOR ALL USING (true) WITH CHECK (true);
